### PR TITLE
add shared vuex-mutations CORE-1298

### PR DESCRIPTION
**Pull request by karladler**
Should be extensively tested before merging. For now tested only in chrome.

- add shared vuex mutations using custom strategy
- implement example use case in mailox dapp to verify that it works

https://evannetwork.atlassian.net/browse/CORE-1298

### CODE REVIEW

**Comment by Tschuck** [comment]
Looks very good and interesting! If we will enhance the vue store more and more, we should maybe create a seperated file for vuex handling, so we will have a better overview about functions and events.

**Comment by karladler** [comment]
> Looks very good and interesting! If we will enhance the vue store more and more, we should maybe create a seperated file for vuex handling, so we will have a better overview about functions and events.

We could introduce some global stores and use Vuex modules for Dapps to plugin into the store.

**Comment by datrinh** [comment]
Can you elaborate on the added package and what we achieve with it? Is there a ticket where it is explained?

**Comment by karladler** [comment]
> Can you elaborate on the added package and what exactly is the motivation behind this? Is there a ticket where it is explained?

There is no ticket (yet) for this. The package is designed to synchronize Vuex state across different tabs nad browser windows. I utilized it to achieve synchronisation between different instances of Vuex store since every dapp initializes the store new and currently Vuex state is not shared between dapps.

Now we have the possibility to sync certain parts of the state across DApps adressing it in the predicate option: https://github.com/evannetwork/ui-dapps/pull/169/files#diff-5ba09729539e688ddbc97f95656e793cR188

**Pull request closed without merging**
